# Generated by Django 4.2.15 on 2025-01-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0033_remove_franchisee_center_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
