# Generated by Django 4.2.15 on 2025-01-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0034_student_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
