# Generated by Django 4.2.15 on 2025-03-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0036_alter_enquiry_phone_country_code_alter_enquiry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='franchisee',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
